X-PhraseApp-OTP:
  in: header
  name: X-PhraseApp-OTP
  description: Two-Factor-Authentication token (optional)
  required: false
  allowEmptyValue: false
  schema:
    type: string
If-Modified-Since:
  description: 'Last modified condition, see <a href="#overview--conditional-get-requests--http-caching">Conditional GET requests / HTTP Caching</a> (optional)'
  explode: false
  in: header
  name: If-Modified-Since
  required: false
  schema:
    type: string
  style: simple
If-None-Match:
  description: 'ETag condition, see <a href="#overview--conditional-get-requests--http-caching">Conditional GET requests / HTTP Caching</a> (optional)'
  explode: false
  in: header
  name: If-None-Match
  required: false
  schema:
    type: string
  style: simple
account_id:
  in: path
  name: account_id
  description: Account ID
  required: true
  schema:
    type: string
custom_metadata_data_type:
  in: query
  name: data_type
  description: Data Type of Custom Metadata Property
  required: false
  schema:
    "$ref": "./schemas/custom_metadata_data_type.yaml#/data_type"
  example: boolean
query_account_id:
  in: query
  name: account_id
  description: Filter by Account ID
  required: false
  schema:
    type: string
space_id:
  in: path
  name: space_id
  description: Space ID
  required: true
  schema:
    type: string
team_id:
  in: path
  name: team_id
  description: Team ID
  required: true
  schema:
    type: string
project_id:
  in: path
  name: project_id
  description: Project ID
  required: true
  schema:
    type: string
key_id:
  in: path
  name: key_id
  description: Translation Key ID
  required: true
  schema:
    type: string
figma_attachment_id:
  in: path
  name: figma_attachment_id
  description: Figma attachment ID
  required: true
  schema:
    type: string
job_id:
  in: path
  name: job_id
  description: Job ID
  required: true
  schema:
    type: string
job_template_id:
  in: path
  name: job_template_id
  description: Job Template ID
  required: true
  schema:
    type: string
job_template_locale_id:
  in: path
  name: job_template_locale_id
  description: Job Template Locale ID
  required: true
  schema:
    type: string
distribution_id:
  in: path
  name: distribution_id
  description: Distribution ID
  required: true
  schema:
    type: string
screenshot_id:
  in: path
  name: screenshot_id
  description: Screenshot ID
  required: true
  schema:
    type: string
translation_id:
  in: path
  name: translation_id
  description: Translation ID
  required: true
  schema:
    type: string
glossary_id:
  in: path
  name: glossary_id
  description: Glossary ID
  required: true
  schema:
    type: string
comment_id:
  in: path
  name: comment_id
  description: Comment ID
  required: true
  schema:
    type: string
term_id:
  in: path
  name: term_id
  description: Term ID
  required: true
  schema:
    type: string
locale_codes:
  in: query
  name: locale_codes
  description: Locale Code
  required: false
  schema:
    type: string
locale_id:
  in: path
  name: locale_id
  description: Locale ID
  required: true
  schema:
    type: string
locale_id_as_id:
  in: path
  name: id
  description: Locale ID or locale name
  required: true
  schema:
    type: string
gitlab_sync_id:
  in: path
  name: gitlab_sync_id
  description: Gitlab Sync ID
  required: true
  schema:
    type: string
id:
  in: path
  name: id
  description: ID
  required: true
  schema:
    type: string
name:
  in: path
  name: name
  description: name
  required: true
  schema:
    type: string
tag:
  in: query
  name: tag
  description: tag
  required: false
  schema:
    type: string
page:
  in: query
  name: page
  description: Page number
  required: false
  allowEmptyValue: false
  schema:
    type: integer
  example: 1
per_page:
  in: query
  name: per_page
  description: Limit on the number of objects to be returned, between 1 and 100. 25 by default
  required: false
  allowEmptyValue: false
  schema:
    type: integer
  example: 25
webhook_id:
  in: path
  name: webhook_id
  description: Webhook ID
  required: true
  schema:
    type: string
response_status_codes:
  in: query
  name: response_status_codes
  description: List of Response Status Codes
  required: false
  schema:
    type: string
