X-PhraseApp-OTP:
  in: header
  name: X-PhraseApp-OTP
  description: Two-Factor-Authentication token (optional)
  required: false
  allowEmptyValue: false
  schema:
    type: string
account_id:
  in: path
  name: account_id
  description: Account ID
  required: true
  schema:
    type: string
query_account_id:
  in: query
  name: account_id
  description: Filter by Account ID
  required: false
  schema:
    type: string
space_id:
  in: path
  name: space_id
  description: Space ID
  required: true
  schema:
    type: string
team_id:
  in: path
  name: team_id
  description: Team ID
  required: true
  schema:
    type: string
project_id:
  in: path
  name: project_id
  description: Project ID
  required: true
  schema:
    type: string
key_id:
  in: path
  name: key_id
  description: Translation Key ID
  required: true
  schema:
    type: string
job_id:
  in: path
  name: job_id
  description: Job ID
  required: true
  schema:
    type: string
distribution_id:
  in: path
  name: distribution_id
  description: Distribution ID
  required: true
  schema:
    type: string
screenshot_id:
  in: path
  name: screenshot_id
  description: Screenshot ID
  required: true
  schema:
    type: string
translation_id:
  in: path
  name: translation_id
  description: Translation ID
  required: true
  schema:
    type: string
glossary_id:
  in: path
  name: glossary_id
  description: Glossary ID
  required: true
  schema:
    type: string
term_id:
  in: path
  name: term_id
  description: Term ID
  required: true
  schema:
    type: string
locale_id:
  in: path
  name: locale_id
  description: Locale ID
  required: true
  schema:
    type: string
gitlab_sync_id:
  in: path
  name: gitlab_sync_id
  description: Gitlab Sync ID
  required: true
  schema:
    type: string
id:
  in: path
  name: id
  description: ID
  required: true
  schema:
    type: string
name:
  in: path
  name: name
  description: name
  required: true
  schema:
    type: string
page:
  in: query
  name: page
  description: Page number
  required: false
  allowEmptyValue: false
  schema:
    type: integer
  example: 1
per_page:
  in: query
  name: per_page
  description: allows you to specify a page size up to 100 items, 25 by default
  required: false
  allowEmptyValue: false
  schema:
    type: integer
  example: 25
