X-PhraseApp-OTP:
  in: header
  name: X-PhraseApp-OTP
  description: Two-Factor-Authentication token
  required: false
  allowEmptyValue: false
  schema:
    type: string
account_id:
  in: path
  name: account_id
  description: Account ID
  required: true
  schema:
    type: string
space_id:
  in: path
  name: space_id
  description: Space ID
  required: true
  schema:
    type: string
project_id:
  in: path
  name: project_id
  description: Project ID
  required: true
  schema:
    type: string
page:
  in: query
  name: page
  description: Page number
  required: false
  allowEmptyValue: false
  schema:
    type: integer
  example: 1
per_page:
  in: query
  name: per_page
  description: allows you to specify a page size up to 100 items, 10 by default
  required: false
  allowEmptyValue: false
  schema:
    type: integer
  example: 10
