name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      -
        name: Version
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      -
        name: Release Github Package
        run: bash ./.github/workflows/release.sh -xe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
          GPG_KEY: |
            ${{ secrets.GPG_KEY }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
