---
- - :inherit_from
  - url: https://raw.githubusercontent.com/phrase/lawa/master/config/license-decisions.yml
    authorization: token $GITHUB_TOKEN
- - :approve
  - json
  - :who: Sönke Behrendt
    :why: ruby license
    :versions: []
    :when: 2025-07-08 15:04:25.587413000 Z
