# coding: utf-8

"""
    Phrase Strings API Reference

    The version of the OpenAPI document: 2.0.0
    Contact: support@phrase.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
from unittest.mock import Mock, patch

import phrase_api
from phrase_api.api.uploads_api import UploadsApi  # noqa: E501
from phrase_api.rest import ApiException


class TestUploadsApi(unittest.TestCase):
    """UploadsApi unit test stubs"""

    def setUp(self):
        self.configuration = phrase_api.Configuration()
        self.configuration.api_key['Authorization'] = 'YOUR_API_KEY'
        self.configuration.api_key_prefix['Authorization'] = 'token'

    def tearDown(self):
        pass

    @patch('phrase_api.ApiClient.request')
    def test_upload_create(self, mock_post):
        """Test case for upload_create

        Upload a new file  # noqa: E501
        """
        mock_post.return_value = Mock(ok=True)
        mock_post.return_value.data = '{"id": "upload_id", "format": "simple_json"}'

        project_id = "project_id_example"
        with phrase_api.ApiClient(self.configuration) as api_client:
            api_instance = phrase_api.UploadsApi(api_client)
            api_response = api_instance.upload_create(
                project_id,
                file="./test/fixtures/en.json",
                file_format="simple_json",
                format_options={"enable_pluralization": True}
            )

            mock_post.assert_called_with("POST", "https://api.phrase.com/v2/projects/project_id_example/uploads", query_params=[], headers={'Accept': 'application/json', 'Content-Type': 'multipart/form-data', 'User-Agent': 'OpenAPI-Generator/1.14.0/python', 'Authorization': 'token YOUR_API_KEY'}, post_params=[('file_format', 'simple_json'), ('format_options', {'enable_pluralization': True}), ('file', ('en.json', b'{\n    "key": "value"\n}\n', 'application/json'))], body=None, _preload_content=True, _request_timeout=None)

            self.assertIsNotNone(api_response)
            self.assertIsInstance(api_response, phrase_api.models.upload.Upload)
            self.assertEqual("upload_id", api_response.id)
            self.assertEqual("simple_json", api_response.format)

    def test_upload_show(self):
        """Test case for upload_show

        Get a single upload  # noqa: E501
        """
        pass

    def test_uploads_list(self):
        """Test case for uploads_list

        List uploads  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
