name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@d3c9825d67b0d8720afdfdde5af56c79fdb38d16 # pin@v1.138.0
        with:
          ruby-version: '3.2'
      -
        name: Version
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      -
        name: Release Github Package
        run: bash ./.github/workflows/release.sh -xe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
          OWNER: phrase
