name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.2'
      -
        name: Version
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      -
        name: Release Github Package
        run: bash ./.github/workflows/release.sh -xe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
          OWNER: phrase
