---
automation:
  type: object
  title: automation
  properties:
    id:
      type: string
    name:
      type: string
    status:
      type: string
      enum: [inactive, active, error]
    trigger:
      "$ref": "#/trigger"
    status_filters:
      "$ref": "#/status_filters"
    project_id:
      type: string
    job_template_id:
      type: string
    tags:
      type: array
      items:
        type: string
    cron_schedule:
      type: string
    time_zone:
      type: string
    account:
      "$ref": "./account.yaml#/account"
    created_at:
      type: string
      format: date-time
    updated_at:
      type: string
      format: date-time
  example:
    id: abcd1234cdef1234abcd1234cdef1234
    name: My First Automation
    status: active
    trigger: schedule
    status_filters:
      - unverified
      - untranslated
      - ready_for_review
    project: project
    job_template: job_template
    tags:
      - tag-1
      - tag-2
    cron_schedule: 00 13 * * 1,2
    time_zone: GMT
    account: account
    created_at: '2021-06-28T09:52:53Z'
    updated_at: '2021-06-28T09:52:53Z'
trigger:
  type: string
  enum: [schedule, upload]
status_filters:
  type: array
  items:
    type: string
    enum: [unverified, untranslated, ready_for_review]
