project:
  type: object
  properties:
    id:
      type: string
    name:
      type: string
    main_format:
      type: string
    project_image_url:
      type: string
    account:
      type: string
    created_at:
      type: string
    updated_at:
      type: string
  example:
    id: abcd1234cdef1234abcd1234cdef1234
    name: My Android Project
    main_format: xml
    project_image_url: http://assets.example.com/project.png
    account: account
    created_at: '2015-01-28T09:52:53Z'
    updated_at: '2015-01-28T09:52:53Z'
