name: License Check
on: push
jobs:
  lawa-npm-ci:
    name: NPM license checks
    uses: phrase/actions/.github/workflows/lawa-npm-ci.yml@main
    with:
      node-version: 18
      ruby-version: 3.1.3
      decisions-file: config/license-decisions.yml
    secrets:
      github-token: ${{ secrets.GH_ACCESS_TOKEN }}
