name: Lint
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: npm install
      - run: npm run lint

  compare-output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: npm install
      - run: npx swagger-cli bundle -t json -w 300 main.yaml > doc/compiled_new.json
      - run: diff doc/compiled.json doc/compiled_new.json

  compile-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.6
      - name: Build
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run generate.go
          cd clients/go && go install ./...

  compile-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.6
      - name: Build
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run generate.cli
          cd clients/cli && go install ./...
