name: Run Java Tests
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run generate.java
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Run gradle test
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.1.1
        build-root-directory: ./clients/java
        arguments: test --info
    - name: License check
      uses: phrase/actions/lawa-ci@81a398057cae95b3433cf798afb5570e04f08d29
      with:
        github-token: ${{ secrets.GH_LAWA_ACCESS_TOKEN }}
        decisions-file: .license-decisions.yml
        ruby-version: 3.3.2
        ruby-bundler-version: 2.3.5
        working-directory: clients/java
        package-managers: gradle
