name: Run Go Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.6'
      - name: Run Tests
        run: |
          npm install
          npm run generate.go
          cd ./clients/go/test
          go test
      - name: License check
        uses: phrase/actions/lawa-ci@v1
        with:
          github-token: ${{ secrets.GH_LAWA_ACCESS_TOKEN }}
          decisions-file: .license-decisions.yml
          working-directory: clients/go
          package-managers: gomodules
