name: Run Java Tests
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run generate.java
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - name: Run gradle test
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.1.1
        build-root-directory: ./clients/java
        arguments: test --info
    - name: License check
      uses: phrase/actions/lawa-ci@v1
      with:
        github-token: ${{ secrets.GH_LAWA_ACCESS_TOKEN }}
        decisions-file: .license-decisions.yml
        working-directory: clients/java
        package-managers: maven