name: Run Python Tests
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run generate.python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          working-directory: ./clients/python
      - name: Run tests
        run: |
          cd ./clients/python
          pip install -r requirements.txt -r test-requirements.txt
          python -m unittest
