name: Run Java Tests
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Run Gradle Tests
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: ./clients/java
        arguments: test
