name: Run Ruby Tests
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run generate.ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
          working-directory: ./clients/ruby
      - name: Run tests
        run: |
          cd ./clients/ruby
          bundle exec rspec
      - name: Check licenses
        uses: phrase/actions/lawa-ruby-ci@57a83463fa1ba669808329d87d1b2616dc4cdeef
        with:
          working-directory: ./clients/ruby
          decisions-file: config/license-decisions.yml
          github-token: ${{ secrets.GH_LAWA_ACCESS_TOKEN }}
