name: Run Typescript Tests
on: [push]
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run generate.typescript
          cd ./clients/typescript
          npm install
          npm test
