name: Run Go Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.6'
      - name: Run Tests
        run: |
          npm install
          npm run generate.go
          cd ./clients/go/test
          go test
  lawa-gomod-ci:
    name: Check licenses
    uses: phrase/actions/.github/workflows/lawa-gomod-ci.yml@tsi-2537-golang
    with:
      working-directory: clients/go
      decisions-file: .license-decisions.yml
      ruby-version: 3.3.2
    secrets:
      github-token: ${{ secrets.GH_LAWA_ACCESS_TOKEN }}
