name: Run Go Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.6'
      - name: Run Tests
        run: |
          npm install
          npm run generate.go
          cd ./clients/go/test
          go test
      - name: License check
        uses: phrase/actions/lawa-gomod-ci@d5a501195117b8ab77a586f5078ebbdbb209393d
        with:
          github-token: ${{ secrets.GH_LAWA_ACCESS_TOKEN }}
          decisions-file: .license-decisions.yml
          ruby-version: 3.3.2
          go-version: 1.19.6
          ruby-bundler-version: 2.3.5
          working-directory: clients/go
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@0cde4689ba33c09f1b890c1725572ad96751a3fc # pin@v1.178.0
      #   with:
      #     ruby-version: 3.3.2
      # - name: Install compatible bundler version
      #   run: gem install bundler
      # - name: Install lawa
      #   run: |
      #     cd ./clients/go
      #     touch Gemfile.lawa
      #     echo "source 'https://rubygems.org'" >> Gemfile.lawa
      #     echo -e "gem 'lawa', github: 'phrase/lawa'" >> Gemfile.lawa
      #     bundle config unset deployment
      #     BUNDLE_GEMFILE=Gemfile.lawa bundle install
      #   env:
      #     BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GH_LAWA_ACCESS_TOKEN }}
      # - name: Run lawa
      #   run: |
      #     cd ./clients/go
      #     BUNDLE_GEMFILE=Gemfile.lawa bundle exec lawa --enabled-package-managers=gomodules --decisions-file=.license-decisions.yml
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_LAWA_ACCESS_TOKEN }}
