name: Run Java Tests
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run generate.java
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.1.1
        build-root-directory: ./clients/java
    - name: Run tests
      run: |
        cd clients/java
        ./gradlew test --info
